# Generated by Django 5.2.17 on 2026-10-09 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('USER_UPDATED', 'User Updated'), ('ITEM_MODERATED', 'Item Moderated'), ('ITEM_HIDDEN', 'Item Hidden'), ('ITEM_RESTORED', 'Item Restored'), ('ITEM_CLOSED', 'Item Closed'), ('CLAIM_APPROVED_ADMIN', 'Claim Approved by Admin'), ('CLAIM_REJECTED_ADMIN', 'Claim Rejected by Admin'), ('CLAIM_INTERVENTION', 'Claim Administrative Intervention'), ('SETTINGS_UPDATED', 'Settings Updated'), ('PERMISSION_CHANGED', 'Permission Changed')], db_index=True, max_length=50)),
                ('target_model', models.CharField(max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=50)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('view_dashboard_stats', 'Can view admin dashboard statistics'), ('manage_users', 'Can manage users in admin dashboard'), ('moderate_items', 'Can moderate items in admin dashboard'), ('manage_claims', 'Can manage claims in admin dashboard'), ('view_audit_logs', 'Can view audit logs'), ('view_email_logs', 'Can view email delivery logs'), ('manage_settings', 'Can manage platform settings')],
                'indexes': [models.Index(fields=['action_type', 'timestamp'], name='admin_dashb_action__09831d_idx'), models.Index(fields=['target_model', 'target_object_id'], name='admin_dashb_target__be0c9f_idx'), models.Index(fields=['actor', 'timestamp'], name='admin_dashb_actor_i_e2f62b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('CLAIM_SUBMITTED', 'Claim Submitted'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('CLAIM_CANCELLED', 'Claim Cancelled'), ('CLAIM_SUPERSEDED', 'Claim Superseded'), ('REPORT_STATUS_CHANGED', 'Report Status Changed'), ('REPORT_MODERATED', 'Report Moderated'), ('ACCOUNT_STATUS_CHANGED', 'Account Status Changed'), ('GENERAL_NOTIFICATION', 'General Notification')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='notifications.notification')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='admin_dashb_status_368626_idx'), models.Index(fields=['event_type', 'status'], name='admin_dashb_event_t_a6bfcb_idx'), models.Index(fields=['recipient_email', 'status'], name='admin_dashb_recipie_833946_idx')],
            },
        ),
    ]
