# Generated by Django 4.2.30 on 2026-09-28 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATCHED', 'Potential Match'), ('CLAIMED', 'Claimed'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('MOBILE', 'Mobile Phone'), ('LAPTOP', 'Laptop'), ('TABLET', 'Tablet'), ('WATCH', 'Watch'), ('WALLET', 'Wallet'), ('BAG', 'Bag'), ('KEYS', 'Keys'), ('DOCUMENT', 'Documents'), ('ID_CARD', 'ID Card'), ('JEWELRY', 'Jewelry'), ('CLOTHING', 'Clothing'), ('ACCESSORY', 'Accessories'), ('BOOK', 'Books'), ('STATIONERY', 'Stationery'), ('VEHICLE', 'Vehicle'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2000)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date_occurred', models.DateField(validators=[items.models.validate_not_future_date])),
                ('time_occurred', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('identification_details', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type'], name='items_item_item_ty_048ead_idx'), models.Index(fields=['category'], name='items_item_categor_db7f55_idx'), models.Index(fields=['status'], name='items_item_status_819478_idx'), models.Index(fields=['location'], name='items_item_locatio_896340_idx'), models.Index(fields=['date_occurred'], name='items_item_date_oc_11804d_idx'), models.Index(fields=['created_at'], name='items_item_created_3cdd06_idx')],
            },
        ),
    ]
