# Generated by Django 5.2.17 on 2026-10-09 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, hides item from public catalog and search results.'),
        ),
        migrations.AddField(
            model_name='item',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Internal staff notes regarding moderation.'),
        ),
        migrations.AddField(
            model_name='item',
            name='moderation_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING_REVIEW', 'Pending Review'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_hidden'], name='items_item_is_hidd_d9dd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['moderation_status'], name='items_item_moderat_2cafd1_idx'),
        ),
    ]
