# Generated by Django 5.2.17 on 2026-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLAIM_SUBMITTED', 'Claim Submitted'), ('CLAIM_APPROVED', 'Claim Approved'), ('CLAIM_REJECTED', 'Claim Rejected'), ('CLAIM_CANCELLED', 'Claim Cancelled'), ('CLAIM_SUPERSEDED', 'Claim Superseded'), ('ITEM_STATUS_CHANGED', 'Item Status Changed'), ('MODERATION_ACTION', 'Moderation Action'), ('ACCOUNT_STATUS_CHANGED', 'Account Status Changed'), ('ADMIN_ALERT', 'Admin Alert')], max_length=30),
        ),
    ]
